name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download deps
      run: |
        sudo apt-get install libpcap-dev
    - name: make
      run: |
        make
        ls -l
