name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download deps
      run: |
        sudo apt-get install libpcap-dev
    - name: make
      run: |
        make
        mkdir out
        cp rsniffer out/
        cp README out/
        ls -l
    - name: Upload binary
      uses: actions/upload-artifact@master
      with:
        name: linux_x86-64
        path: out
